<?php
/**
 * @file
 * Code for the Cedi Panopoly feature.
 */

include_once 'cedi_panopoly.features.inc';
/**
 * @file
 * Custom CEDI module used for the Panopoly distribution.
 */

function cedi_panopoly_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // Move my_module_hook() to the end of the list. module_implements()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['cedi_panopoly'];
    unset($implementations['cedi_panopoly']);
    $implementations['cedi_panopoly'] = $group;
  }
}

/**
 * Allows us to set an 'Admin Title' on panel panes without requiring them to be
 * reusable pieces of content.
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function cedi_panopoly_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'views_content_views_panes_content_type_edit_form') {
//    drupal_add_css(drupal_get_path('module', 'cedi_panopoly') . '/panopoly.css', array('group' => CSS_THEME, 'every_page' => FALSE));
  }
  if ($form_id == 'fieldable_panels_panes_entity_edit_form') {
    // Unset the dependency on the reusable checkbox so we can add an admin title
    // and an admin description without making it reusable.
    unset($form['reusable']['admin_title']['#dependency']);
    unset($form['reusable']['admin_description']['#dependency']);
  }
  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {
    // Unset the dependency on the reusable checkbox so we can add an admin title
    // and an admin description without making it reusable.
    unset($form['widget_settings']['reusable']['admin_title']['#dependency']);
    unset($form['widget_settings']['reusable']['admin_description']['#dependency']);

  }
  if ($form_id === 'file_entity_add_upload' || $form_id === 'file_entity_edit') {
    // Add a description to the 'Name' field.
    $form['filename']['#description'] = '<span class="error">' . t('NOTICE: If this is a file that is used for something other than content...') . '</span>' . t('Please change the filename to something like:
    PAGE--DESCRIPTION. e.g., home-slider--empire-state-building OR event-calendar--top-image');
  }
}

function cedi_panopoly_node_view($node, $view_mode, $langcode) {
  // Add css_class to all panelizer teaser view modes for nodes. Do this here
  // instead of in the UI.
  if (!empty($node->panelizer)) {
    if (isset($node->panelizer[$view_mode])) {
      $class = str_replace(':', '-', $node->panelizer[$view_mode]->name);
      $node->panelizer[$view_mode]->css_class = $class;
    }
  }
}
